### ISSUE TITLE
running  diversity/runner.sh scripts takes longer time in GPU server

### ISSUE THREAD

**Issue by narayanal** [alycialee/beyond-scale-language-data-diversity#11]
What is the approximate time taken to run the scripts diversity/runner.sh.
In my GPU server set-up, it takes more than 10 hrs.

Is there any other way for this

**Comment by alycialee** [comment]
That is roughly the amount of time it took when I ran the script. Because the datasets are streamed, there's network latency when getting a batch of data. That latency isn't realized until batches are enumerated in epoch_iterator from the data_loader. To reduce this latency, you can download all or at least a subset of the data from HF and store on disk. Downloading only a subset of the idea is likely more feasible (depending on your experimental setup / machine specs), but isn't ideal since it means we'd only randomly sample tasks from a subset of the data and may not be fair for computing diversity.
